version: "3.9"

services:
  app:
    build: .
    ports:
      - "8001:8001"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: mysql_BookingSchedue
      DB_USER: root
      DB_PASS: 1234
    depends_on:
      - db

  db:
    image: mysql:5.7
    ports:
      - "3306:3306" # Cổng của MySQL
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: mysql_BookingSchedue
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
